In [25]:
import pandas as pd

### Load Data

In [26]:
df = pd.read_csv("air_quality_by_state_county.csv")
df.head()

,index,MeasureId,MeasureName,MeasureType,StratificationLevel,StateFips,StateName,CountyFips,CountyName,ReportYear,Value,Unit,UnitName,DataOrigin,MonitorOnly
0,0,83,Number of days with maximum 8-hour average ozo...,Counts,State x County,1,Alabama,1051,Elmore,1999,5.0,No Units,No Units,Monitor Only,1
1,1,83,Number of days with maximum 8-hour average ozo...,Counts,State x County,1,Alabama,1073,Jefferson,1999,39.0,No Units,No Units,Monitor Only,1
2,2,83,Number of days with maximum 8-hour average ozo...,Counts,State x County,1,Alabama,1079,Lawrence,1999,28.0,No Units,No Units,Monitor Only,1
3,3,83,Number of days with maximum 8-hour average ozo...,Counts,State x County,1,Alabama,1089,Madison,1999,31.0,No Units,No Units,Monitor Only,1
4,4,83,Number of days with maximum 8-hour average ozo...,Counts,State x County,1,Alabama,1097,Mobile,1999,32.0,No Units,No Units,Monitor Only,1

# Do 5 data transformations

### Convert Value to a consistent numeric format

In [27]:
df['Value'] = pd.to_numeric(df['Value'], errors='coerce')

### Drop duplicates

In [28]:
df = df.drop_duplicates()

### Make new Column for county and state together

In [29]:
# There are some instances where Counties can match multiple states, so we're going to create unique identifiers
df['StateAndCounty'] = df['CountyName'].str.strip() + '_' + df['StateName'].str.strip()
# After this, we don't need the county name, so we'll drop it
df = df.drop(columns=['CountyName'])

### Drop Columns that are not needed

In [30]:
# The reason I'm dropping fips is because each simple corresponds to a location id. For example, every row with "Alabama" will have the same fips code. This is basically an encoded variable. Because we're already encoding our own variables, we don't need fips
df = df.drop(columns=['StateFips', 'CountyFips'])

# Dropping index because it isn't needed, it's going to present in a DF anyway
df = df.drop(columns=['index'])

# Dropping MeasureId since it's just the encoded version of the MeasureName
df = df.drop(columns=['MeasureId'])

df.columns

Index(['MeasureName', 'MeasureType', 'StratificationLevel', 'StateName',
       'ReportYear', 'Value', 'Unit', 'UnitName', 'DataOrigin', 'MonitorOnly',
       'StateAndCounty'],
      dtype='object')

### Standardize column names

In [32]:
cols_to_encode = [
    'MeasureName', 'MeasureType', 'StratificationLevel', 'StateName',
    'Unit', 'UnitName', 'DataOrigin', 'MonitorOnly'
]

for col in cols_to_encode:
    df[col], _ = pd.factorize(df[col])

df.head()

,MeasureName,MeasureType,StratificationLevel,StateName,ReportYear,Value,Unit,UnitName,DataOrigin,MonitorOnly,StateAndCounty
0,0,0,0,0,1999,5.0,0,0,0,0,Elmore_Alabama
1,0,0,0,0,1999,39.0,0,0,0,0,Jefferson_Alabama
2,0,0,0,0,1999,28.0,0,0,0,0,Lawrence_Alabama
3,0,0,0,0,1999,31.0,0,0,0,0,Madison_Alabama
4,0,0,0,0,1999,32.0,0,0,0,0,Mobile_Alabama