## Author: Gabriel Vance
## Class: DSC550 - Data Mining
## Professor: Dr. Brett Werner
## Date: June 9, 2025

# Purpose: This notebook performs the tasks outlined in 1.2 Assignment: R/Python Refresher.

Requirements

You must use all 3 datasets provided to provide a visual story with the data with whatever medium you are choosing to present your story and remember it must include a call to action.
This exercise can use PowerBI/Tableau/R or Python. Make sure to carefully check each exercise, as some exercises will require a specific tool be used.
You must define an audience, purpose, and medium to tell your story.
You must have at least 6 visuals included that use the data provided.
Include a 250-500-word paper summarizing your audience, purpose, medium and design choices along with the above ethical consideration questions.

Netflix is at an existential breaking point. The financial environment has changed dramatically, and we must pivot to survive. Plain and simple, hit shows retain subscribers. We need more hit shows. Data collection from users gives us insights into the top content on Netflix.

Audience: Netflix Executives
Purpose: Find trends in viewership data to guide content creation and acquisition strategies.
Medium: Powerpoint

In [1]:
import pandas as pd

In [2]:
# Read in the Excel files
all_weeks_countries_netflix = pd.read_excel('all-weeks-countries-netflix.xlsx')
all_weeks_global_netflix = pd.read_excel('all-weeks-global-netflix.xlsx')
most_popular_netflix = pd.read_excel('most-popular-netflix.xlsx')

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [9]:
all_weeks_countries_netflix.head(10)

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
0,Argentina,AR,2024-04-14,Films,1,The Tearsmith,NaN,2
1,Argentina,AR,2024-04-14,Films,2,Stolen,NaN,1
2,Argentina,AR,2024-04-14,Films,3,"Love, Divided",NaN,1
3,Argentina,AR,2024-04-14,Films,4,Woody Woodpecker Goes to Camp,NaN,1
4,Argentina,AR,2024-04-14,Films,5,Rest In Peace,NaN,3
5,Argentina,AR,2024-04-14,Films,6,What Jennifer Did,NaN,1
6,Argentina,AR,2024-04-14,Films,7,Scoop,NaN,1
7,Argentina,AR,2024-04-14,Films,8,The Wages of Fear,NaN,3
8,Argentina,AR,2024-04-14,Films,9,The Beautiful Game,NaN,2
9,Argentina,AR,2024-04-14,Films,10,Room,NaN,1

In [10]:
all_weeks_global_netflix.head(10)

,week,category,weekly_rank,show_title,season_title,weekly_hours_viewed,runtime,weekly_views,cumulative_weeks_in_top_10,is_staggered_launch,episode_launch_details
0,2024-04-14,Films (English),1,What Jennifer Did,NaN,26100000,1.4500,18000000.0,1,False,NaN
1,2024-04-14,Films (English),2,Woody Woodpecker Goes to Camp,NaN,19600000,1.6667,11800000.0,1,False,NaN
2,2024-04-14,Films (English),3,Scoop,NaN,14600000,1.7167,8500000.0,2,False,NaN
3,2024-04-14,Films (English),4,Glass,NaN,11000000,2.1500,5100000.0,2,False,NaN
4,2024-04-14,Films (English),5,Megan Leavey,NaN,9700000,1.9333,5000000.0,1,False,NaN
5,2024-04-14,Films (English),6,The Bricklayer,NaN,8500000,1.8333,4600000.0,1,False,NaN
6,2024-04-14,Films (English),7,Hotel Transylvania 2,NaN,5200000,1.5000,3500000.0,5,False,NaN
7,2024-04-14,Films (English),8,The Little Things,NaN,7300000,2.1333,3400000.0,2,False,NaN
8,2024-04-14,Films (English),9,The Maze Runner,NaN,6000000,1.8833,3200000.0,2,False,NaN
9,2024-04-14,Films (English),10,Heart of the Hunter,NaN,5600000,1.7833,3100000.0,3,False,NaN

In [11]:
most_popular_netflix.head(10)

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
4,Films (English),5,Leave the World Behind,NaN,339300000,2.3667,143400000
5,Films (English),6,The Gray Man,NaN,299500000,2.1500,139300000
6,Films (English),7,We Can Be Heroes,NaN,231200000,1.6833,137300000
7,Films (English),8,The Mother,NaN,265900000,1.9500,136400000
8,Films (English),9,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000
9,Films (English),10,Extraction,NaN,266900000,1.9667,135700000