## Author: Gabriel Vance
## Class: DSC550 - Data Mining
## Professor: Dr. Brett Werner
## Date: June 9, 2025

# Purpose: This notebook performs various tasks labeled "Exercises" for Week 1 of the class. Data must be present within the folder that this notebook is run in.
# This week focuses on Exploring Data

In [32]:
import kagglehub
import pandas as pd

# Exercise

## Load the dataset as a Pandas data frame.

In [33]:
# Optionally download from here


# # Download latest version
# path = kagglehub.dataset_download("rush4ratio/video-game-sales-with-ratings")

# print("Path to dataset files:", path)

# Or load data directly from CSV
df = pd.read_csv('video_games.csv')

## Display the first ten rows of data.

In [34]:
# Display the first 10 rows of the dataset using head()
df.head(10)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
5,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,NaN,NaN,NaN,NaN,NaN,NaN
6,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.28,9.14,6.50,2.88,29.80,89.0,65.0,8.5,431.0,Nintendo,E
7,Wii Play,Wii,2006.0,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E
8,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.44,6.94,4.70,2.24,28.32,87.0,80.0,8.4,594.0,Nintendo,E
9,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31,NaN,NaN,NaN,NaN,NaN,NaN

## Find the dimensions (number of rows and columns) in the data frame. What do these two numbers represent in the context of the data?

In [35]:
# Check the shape, using rows and columns
rows, columns = df.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")

print("Rows are the number of video games, and columns are the attributes of each game.")

Number of rows: 16719
Number of columns: 16
Rows are the number of video games, and columns are the attributes of each game.

## Find the top five games by critic score.

In [36]:
# Sort df by Critic_Score
top5_critic = df.sort_values(by='Critic_Score', ascending=False)
# Print the top 5 rows of the sorted DataFrame
top5_critic.head(5)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
227,Tony Hawk's Pro Skater 2,PS,2000.0,Sports,Activision,3.05,1.41,0.02,0.20,4.68,98.0,19.0,7.7,299.0,Neversoft Entertainment,T
57,Grand Theft Auto IV,PS3,2008.0,Action,Take-Two Interactive,4.76,3.69,0.44,1.61,10.50,98.0,64.0,7.5,2833.0,Rockstar North,M
51,Grand Theft Auto IV,X360,2008.0,Action,Take-Two Interactive,6.76,3.07,0.14,1.03,11.01,98.0,86.0,7.9,2951.0,Rockstar North,M
5350,SoulCalibur,DC,1999.0,Fighting,Namco Bandai Games,0.00,0.00,0.34,0.00,0.34,98.0,24.0,8.8,200.0,Namco,T
165,Grand Theft Auto V,XOne,2014.0,Action,Take-Two Interactive,2.81,2.19,0.00,0.47,5.48,97.0,14.0,7.9,764.0,Rockstar North,M

## Find the number of video games in the data frame in each genre.

In [37]:
# Use value_counts() to count the number of games in each genre
genre_counts = df['Genre'].value_counts()
genre_counts

Genre
Action          3370
Sports          2348
Misc            1750
Role-Playing    1500
Shooter         1323
Adventure       1303
Racing          1249
Platform         888
Simulation       874
Fighting         849
Strategy         683
Puzzle           580
Name: count, dtype: int64

## Find the first five games in the data frame on the SNES platform.

In [38]:
# Display the first 5 rows, using the sorted df. Filter by Platform 'SNES'
top5_critic[top5_critic['Platform'] == 'SNES'].head(5)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
18,Super Mario World,SNES,1990.0,Platform,Nintendo,12.78,3.75,3.54,0.55,20.61,NaN,NaN,NaN,NaN,NaN,NaN
56,Super Mario All-Stars,SNES,1993.0,Platform,Nintendo,5.99,2.15,2.12,0.29,10.55,NaN,NaN,NaN,NaN,NaN,NaN
71,Donkey Kong Country,SNES,1994.0,Platform,Nintendo,4.36,1.71,3.00,0.23,9.30,NaN,NaN,NaN,NaN,NaN,NaN
76,Super Mario Kart,SNES,1992.0,Racing,Nintendo,3.54,1.24,3.81,0.18,8.76,NaN,NaN,NaN,NaN,NaN,NaN
137,Street Fighter II: The World Warrior,SNES,1992.0,Fighting,Capcom,2.47,0.83,2.87,0.12,6.30,NaN,NaN,NaN,NaN,NaN,NaN

## Find the five publishers with the highest total global sales. Note: You will need to calculate the total global sales for each publisher to do this.

In [39]:
# Group the data by 'Publisher'
grouped = df.groupby('Publisher')

# Sum the 'Global_Sales'
publisher_sales = grouped['Global_Sales'].sum()

# Sort the summed sales in descending order. This gives us the highest total sales.
sorted_sales = publisher_sales.sort_values(ascending=False)

# Select the top 5 publishers
top5_publishers = sorted_sales.head(5)

top5_publishers

Publisher
Nintendo                       1788.81
Electronic Arts                1116.96
Activision                      731.16
Sony Computer Entertainment     606.48
Ubisoft                         471.61
Name: Global_Sales, dtype: float64

## Create a new column in the data frame that calculates the percentage of global sales from North America. Display the first five rows of the new data frame.

In [40]:
# Divide NA sales by Global Sales to get the percentage of NA sales. We could also add all of the other regions and the NA together.
df['NA_Global_Sales_As_A_Percentage'] = (df['NA_Sales'] / df['Global_Sales']) * 100
df.head(5)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,NA_Global_Sales_As_A_Percentage
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E,50.115110
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN,72.266402
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,44.144144
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E,47.635032
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN,35.926044

## Find the number NaN entries (missing data values) in each column.

In [41]:
# Get the NA items and their sum
missing_values = df.isna().sum()
# Print the missing values for each column
missing_values

Name                                  2
Platform                              0
Year_of_Release                     269
Genre                                 2
Publisher                            54
NA_Sales                              0
EU_Sales                              0
JP_Sales                              0
Other_Sales                           0
Global_Sales                          0
Critic_Score                       8582
Critic_Count                       8582
User_Score                         6704
User_Count                         9129
Developer                          6623
Rating                             6769
NA_Global_Sales_As_A_Percentage       0
dtype: int64

## Try to calculate the median user score of all the video games. You will likely run into an error because some of the user score entries are a non-numerical string that cannot be converted to a float. Find and replace this string with NaN and then calculate the median. Then, replace all NaN entries in the user score column with the median value.

In [42]:
# Convert 'User_Score' to numeric, coercing errors to NaN
df['User_Score'] = pd.to_numeric(df['User_Score'], errors='coerce')

# Calculate the median, ignoring NaN values
median_user_score = df['User_Score'].median()

# Replace NaN values with the median
df['User_Score'].fillna(median_user_score, inplace=True)

print(f"Median User Score: {median_user_score}")
df.head()

Median User Score: 7.5

C:\Users\Gabe\AppData\Local\Temp\ipykernel_35788\2690099044.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['User_Score'].fillna(median_user_score, inplace=True)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,NA_Global_Sales_As_A_Percentage
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,50.115110
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,7.5,NaN,NaN,NaN,72.266402
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,44.144144
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,47.635032
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,7.5,NaN,NaN,NaN,35.926044