## Author: Gabriel Vance
## Class: DSC530 - Data Exporation and Analysis
## Professor: Matthew Metzger
## Date: March 8, 2025

# Purpose: This notebook performs various tasks labeled "Exercises" for Week 1 & 2 of the class. Data must be present within the folder that this notebook is run in.

## Exercise 1
## Read CSVs into dfs and save results to a single CSV

### Imports

In [ ]:
import pandas as pd

### Dataframe concation

In [2]:
# Read all CSVs into dataframes
aapl_df = pd.read_csv("aapl.csv")
amzn_df = pd.read_csv("amzn.csv")
fb_df = pd.read_csv("fb.csv")
goog_df = pd.read_csv("goog.csv")
nflx_df = pd.read_csv("nflx.csv")

# Add ticker column
aapl_df['ticker'] = "AAPL"
amzn_df['ticker'] = "AMZN"
fb_df['ticker'] = "FB"
goog_df['ticker'] = "GOOG"
nflx_df['ticker'] = "NFLX"

### Concat df into single df

In [3]:
# pd concat returns combined df. ignore index to give us a new index
combined_df = pd.concat([aapl_df, amzn_df, fb_df, goog_df, nflx_df], ignore_index=True)
# Index set to false, otherwise we get and empty column with values 0,1,2,3,4, etc.
combined_df.to_csv("faang.csv", index=False)

## Exercise 2
## Convert date column to datetime and volume col into int. Sort by date, then ticker

In [4]:
faang_df = pd.read_csv("faang.csv")
faang_df.dtypes
#? volume was already of type int?

date       object
open      float64
high      float64
low       float64
close     float64
volume      int64
ticker     object
dtype: object

In [5]:
faang_df['date'] = pd.to_datetime(faang_df['date'], format='%Y-%m-%d')
faang_df['volume'] = faang_df['volume'].astype(int)
faang_df.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

### Sort by primary and secondary columns

In [6]:
# print the current df
faang_df

           date      open      high       low     close    volume ticker
0    2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1    2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2    2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3    2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4    2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL
...         ...       ...       ...       ...       ...       ...    ...
1250 2018-12-24  242.0000  250.6500  233.6800  233.8800   9547616   NFLX
1251 2018-12-26  233.9200  254.5000  231.2300  253.6700  14402735   NFLX
1252 2018-12-27  250.1100  255.5900  240.1000  255.5650  12235217   NFLX
1253 2018-12-28  257.9400  261.9144  249.8000  256.0800  10987286   NFLX
1254 2018-12-31  260.1600  270.1001  260.0000  267.6600  13508920   NFLX

[1255 rows x 7 columns]

In [7]:
# Simple sort, list columns in order to achieve different sorts. Both ascending.
#! note: sort_values RETURNS a df
sorted_by_date = faang_df.sort_values(by=['date', 'ticker'], ascending=[True, True])
sorted_by_date

           date       open       high        low      close    volume ticker
0    2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
251  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
502  2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
753  2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
1004 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX
...         ...        ...        ...        ...        ...       ...    ...
250  2018-12-31   157.8529   158.6794   155.8117   157.0663  35003466   AAPL
501  2018-12-31  1510.8000  1520.7600  1487.0000  1501.9700   6954507   AMZN
752  2018-12-31   134.4500   134.6400   129.9500   131.0900  24625308     FB
1003 2018-12-31  1050.9600  1052.7000  1023.5900  1035.6100   1493722   GOOG
1254 2018-12-31   260.1600   270.1001   260.0000   267.6600  13508920   NFLX

[1255 rows x 7 columns]

## Exercise 3
## Find 7 rows with lowest volume

In [8]:
# sort volume, ascending. Take the top 7 and these will be the lowest value
sorted_by_volume = faang_df.sort_values(by=['volume'],ascending=[True])
sorted_by_volume.head(7)

          date     open     high      low    close  volume ticker
879 2018-07-03  1135.82  1135.82  1100.02  1102.89  679034   GOOG
979 2018-11-23  1030.00  1037.59  1022.40  1023.88  691462   GOOG
852 2018-05-24  1079.00  1080.47  1066.15  1079.24  766773   GOOG
883 2018-07-10  1156.98  1159.59  1149.59  1152.84  798412   GOOG
905 2018-08-09  1249.90  1255.54  1246.01  1249.10  848601   GOOG
912 2018-08-20  1205.02  1211.00  1194.63  1207.77  870772   GOOG
914 2018-08-22  1200.00  1211.84  1199.00  1207.33  887389   GOOG

## Exercise 4 
## Change wide data to long using melt

### Note: 
### Wide data means a single row with multiple time points. 
### Long data would break out the columns into new rows. 

Wide Example: 

Store, Jan Sales, Feb Sales, Mar Sales

Long Example:
Store, Sales, Month (Jan, Feb, Mar)

melt() will allow us to convert from wide to long

In [9]:
# Use melt() to make it completely long format.

# id_vars (not melted). Think keys/composite keys.
id_vars = ['ticker','date']
value_vars = ["open", "high", "low", "close", "volume"]
# var_name is the name of the new column to represent data types (think categorical for stocks)
# value_name will contain the actual data from the original columns
faang_long = faang_df.melt(id_vars=id_vars, value_vars=value_vars,var_name='long metric', value_name='long value')
print(faang_long)

     ticker       date long metric    long value
0      AAPL 2018-01-02        open  1.669271e+02
1      AAPL 2018-01-03        open  1.692521e+02
2      AAPL 2018-01-04        open  1.692619e+02
3      AAPL 2018-01-05        open  1.701448e+02
4      AAPL 2018-01-08        open  1.710375e+02
...     ...        ...         ...           ...
6270   NFLX 2018-12-24      volume  9.547616e+06
6271   NFLX 2018-12-26      volume  1.440274e+07
6272   NFLX 2018-12-27      volume  1.223522e+07
6273   NFLX 2018-12-28      volume  1.098729e+07
6274   NFLX 2018-12-31      volume  1.350892e+07

[6275 rows x 4 columns]

## Exercise 5
## Suppose we found out that on July 26, 2018 there was a glitch in how the data was recorded. How should we handle this? Note that there is no coding required for this exercise.

If we found out there was a glitch in the data and it was malformed, we could investigate the glitch and attempt to find the root cause. This could be a re-occurring problem which might show up again. However, for simplicity sake and data integrity, we will simply drop all rows whose date corresponds to July 26, 2018.

## Exercise 6

* Read Covid data into dataframe
* Create column using the dateRep column and convert to datetime
* Set date column to index
* Replace long name with short name for USA/UK (use replace())
* Filter data using countries column for Argentina, Brazil, China, Colombia, India, Italy, Mexico, Peru, Russia, Spain, Turkey, the UK, and the USA.
* Fill NaN with 0. Pivot so date is index, Columns contain country names, values are cases

In [10]:
# read to dataframe
covid19_data = pd.read_csv("covid19.csv")



# create column
covid19_data['DateRep_as_DateTime'] = pd.to_datetime(covid19_data['dateRep'], format='%d/%m/%Y')
# set as index
covid19_data.set_index('DateRep_as_DateTime', inplace=True)

# short name/long name dict 
short_name_long_name = {
    'United States': 'USA',
    'United Kingdom': 'UK'
}

# replace long names with short names
covid19_data['countriesAndTerritories'] = covid19_data['countriesAndTerritories'].replace(short_name_long_name)

# Make a list of countries we want to use/keep
countries_list = [
    'Argentina', 'Brazil', 'China', 'Colombia', 'India', 'Italy', 
    'Mexico', 'Peru', 'Russia', 'Spain', 'Turkey', 'United Kingdom', 'USA'
]

# filter df if country in country lsit
filtered_data = covid19_data[covid19_data['countriesAndTerritories'].isin(countries_list)]

# double check the state/shape of filtered data, note that Argentina is now the first country instead of afghanistan
filtered_data

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
DateRep_as_DateTime,,,,,,,,,,,,
2020-12-14,14/12/2020,14,12,2020,3558,98,Argentina,AR,ARG,44780675.0,America,177.232701
2020-12-13,13/12/2020,13,12,2020,5274,62,Argentina,AR,ARG,44780675.0,America,181.417542
2020-12-12,12/12/2020,12,12,2020,7112,175,Argentina,AR,ARG,44780675.0,America,183.257622
2020-12-11,11/12/2020,11,12,2020,6994,209,Argentina,AR,ARG,44780675.0,America,184.896722
2020-12-10,10/12/2020,10,12,2020,5303,213,Argentina,AR,ARG,44780675.0,America,189.472356
...,...,...,...,...,...,...,...,...,...,...,...,...
2020-03-18,18/03/2020,18,3,2020,51,0,Turkey,TR,TUR,82003882.0,Europe,NaN
2020-03-17,17/03/2020,17,3,2020,29,0,Turkey,TR,TUR,82003882.0,Europe,NaN
2020-03-16,16/03/2020,16,3,2020,16,0,Turkey,TR,TUR,82003882.0,Europe,NaN
2020-03-13,13/03/2020,13,3,2020,1,0,Turkey,TR,TUR,82003882.0,Europe,NaN
2020-03-12,12/03/2020,12,3,2020,1,0,Turkey,TR,TUR,82003882.0,Europe,NaN

In [11]:
# fill NAs to be 0
filtered_data.fillna(0, inplace=True)

# Pivot the dataframe
pivoted_data = filtered_data.pivot_table(
    index='DateRep_as_DateTime', 
    columns='countriesAndTerritories', 
    # using cases to be the values for the rows
    values='cases', 
    # the sum function wasn't necessary as rows didn't have the same date, but this got rid of floats
    aggfunc='sum', 
    fill_value=0 # if there are any leftover values
)
# pivot table with cases as values
pivoted_data

/var/folders/11/dxk146610qn60jn0f0xly1800000gn/T/ipykernel_72425/1317025210.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data.fillna(0, inplace=True)

countriesAndTerritories,Argentina,Brazil,China,Colombia,India,Italy,Mexico,Peru,Russia,Spain,Turkey
DateRep_as_DateTime,,,,,,,,,,,
2019-12-31,0,0,27,0,0,0,0,0,0,0,0
2020-01-01,0,0,0,0,0,0,0,0,0,0,0
2020-01-02,0,0,0,0,0,0,0,0,0,0,0
2020-01-03,0,0,17,0,0,0,0,0,0,0,0
2020-01-04,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2020-12-10,5303,53453,12,7523,31521,12755,21974,691,26190,7955,31712
2020-12-11,6994,53347,15,7778,29398,16998,11897,1799,27927,10519,30424
2020-12-12,7112,54428,13,8998,30006,18726,12253,1832,28585,0,0
2020-12-13,5274,43900,24,8163,30254,19902,12057,2102,28137,0,32106
2020-12-14,3558,21825,12,8702,27071,17937,8608,1928,28080,0,29136